# Generated by Django 5.2.5 on 2025-10-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_notificationtype_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
