# Generated by Django 5.2.5 on 2025-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0002_impuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('CLASIFICACION', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=40)),
                ('AGRUPACION', models.IntegerField()),
                ('USA_NUMEROS_SERIE', models.CharField(max_length=1)),
                ('PLANTILLA_SERIE', models.CharField(blank=True, max_length=4, null=True)),
                ('APORTE_CODIGO', models.CharField(blank=True, max_length=5, null=True)),
                ('TIPO_CODIGO_BARRAS', models.CharField(blank=True, max_length=1, null=True)),
                ('UNIDAD_MEDIDA', models.CharField(max_length=6)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Clasificacion',
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
    ]
