# Generated by Django 5.2.5 on 2025-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0003_clasificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaLote',
            fields=[
                ('BODEGA', models.CharField(max_length=4)),
                ('ARTICULO', models.CharField(max_length=20)),
                ('LOCALIZACION', models.CharField(max_length=8)),
                ('LOTE', models.CharField(max_length=15)),
                ('CANT_DISPONIBLE', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_RESERVADA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_NO_APROBADA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_VENCIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_REMITIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('COSTO_UNT_PROMEDIO_LOC', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_UNT_PROMEDIO_DOL', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_UNT_ESTANDAR_LOC', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_UNT_ESTANDAR_DOL', models.DecimalField(decimal_places=8, max_digits=28)),
                ('NoteExistsFlag', models.SmallIntegerField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('BODEGA', 'ARTICULO', 'LOCALIZACION', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Lot Stock Availability',
                'verbose_name_plural': 'Lot Stock Availabilities',
            },
        ),
    ]
