# Generated by Django 5.2.5 on 2025-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0004_existencialote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPrecio',
            fields=[
                ('NIVEL_PRECIO', models.CharField(max_length=12)),
                ('MONEDA', models.CharField(max_length=1)),
                ('VERSION', models.IntegerField()),
                ('ARTICULO', models.CharField(max_length=20)),
                ('VERSION_ARTICULO', models.IntegerField()),
                ('PRECIO', models.DecimalField(decimal_places=8, max_digits=28)),
                ('ESQUEMA_TRABAJO', models.CharField(max_length=1)),
                ('MARGEN_MULR', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('MARGEN_UTILIDAD', models.DecimalField(decimal_places=8, max_digits=28)),
                ('FECHA_INICIO', models.DateTimeField()),
                ('FECHA_FIN', models.DateTimeField()),
                ('FECHA_ULT_MODIF', models.DateTimeField(blank=True, null=True)),
                ('USUARIO_ULT_MODIF', models.CharField(blank=True, max_length=50, null=True)),
                ('MARGEN_UTILIDAD_MIN', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('NIVEL_PRECIO', 'MONEDA', 'VERSION', 'ARTICULO', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Article Price',
                'verbose_name_plural': 'Article Price',
            },
        ),
    ]
