# Generated by Django 5.2.5 on 2025-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0005_articuloprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloEnsamble',
            fields=[
                ('ARTICULO_PADRE', models.CharField(max_length=20)),
                ('ARTICULO_HIJO', models.CharField(max_length=20)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('NoteExistsFlag', models.SmallIntegerField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('ARTICULO_PADRE', 'ARTICULO_HIJO', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Articulo Ensamble',
                'verbose_name_plural': 'Articulo Ensambles',
            },
        ),
    ]
