# Generated by Django 5.2.5 on 2025-08-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0006_articuloensamble'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistenciaBodega',
            fields=[
                ('ARTICULO', models.CharField(max_length=20)),
                ('BODEGA', models.CharField(max_length=4)),
                ('EXISTENCIA_MINIMA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('EXISTENCIA_MAXIMA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('PUNTO_DE_REORDEN', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_DISPONIBLE', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_RESERVADA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_NO_APROBADA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_VENCIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_TRANSITO', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_PRODUCCION', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_PEDIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_REMITIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CONGELADO', models.CharField(max_length=1)),
                ('FECHA_CONG', models.DateTimeField(blank=True, null=True)),
                ('BLOQUEA_TRANS', models.CharField(max_length=1)),
                ('FECHA_DESCONG', models.DateTimeField(blank=True, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('COSTO_UNT_PROMEDIO_LOC', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_UNT_PROMEDIO_DOL', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_UNT_ESTANDAR_LOC', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_UNT_ESTANDAR_DOL', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_PROM_COMPARATIVO_LOC', models.DecimalField(decimal_places=8, max_digits=28)),
                ('COSTO_PROM_COMPARATIVO_DOLAR', models.DecimalField(decimal_places=8, max_digits=28)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('ARTICULO', 'BODEGA', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Existencia Bodega',
                'verbose_name_plural': 'Existencia Bodegas',
            },
        ),
    ]
