# Generated by Django 5.2.5 on 2025-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0009_itemmasterview_solicitudoc_solicitudoclinea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsyncmanager',
            name='task_id',
            field=models.CharField(max_length=255, verbose_name='Task ID'),
        ),
    ]
