# Generated by Django 5.2.5 on 2025-08-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0010_alter_modelsyncmanager_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('DEPARTAMENTO', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=254)),
                ('JEFE', models.CharField(blank=True, max_length=250, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('ACTIVO', models.CharField(max_length=1)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
