# Generated by Django 5.2.5 on 2025-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0013_detdocumentoembarque_detlinembarque_devollinembarque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTransInv',
            fields=[
                ('AUDIT_TRANS_INV', models.IntegerField(primary_key=True, serialize=False)),
                ('CONSECUTIVO', models.CharField(blank=True, max_length=10, null=True)),
                ('USUARIO', models.CharField(max_length=50)),
                ('FECHA_HORA', models.DateTimeField()),
                ('MODULO_ORIGEN', models.CharField(max_length=4)),
                ('APLICACION', models.CharField(max_length=249)),
                ('REFERENCIA', models.CharField(max_length=200)),
                ('ASIENTO', models.CharField(blank=True, max_length=10, null=True)),
                ('USUARIO_APRO', models.CharField(blank=True, max_length=50, null=True)),
                ('FECHA_HORA_APROB', models.DateTimeField(blank=True, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('PAQUETE_INVENTARIO', models.CharField(blank=True, max_length=4, null=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Audit Trans Inv',
                'verbose_name_plural': 'Audit Trans Invs',
            },
        ),
        migrations.CreateModel(
            name='TransaccionInv',
            fields=[
                ('AUDIT_TRANS_INV', models.IntegerField()),
                ('CONSECUTIVO', models.IntegerField()),
                ('FECHA_HORA_TRANSAC', models.DateTimeField(blank=True, null=True)),
                ('NIT', models.CharField(blank=True, max_length=20, null=True)),
                ('SERIE_CADENA', models.IntegerField(blank=True, null=True)),
                ('AJUSTE_CONFIG', models.CharField(blank=True, max_length=4, null=True)),
                ('ARTICULO', models.CharField(max_length=20)),
                ('BODEGA', models.CharField(blank=True, max_length=4, null=True)),
                ('LOCALIZACION', models.CharField(blank=True, max_length=8, null=True)),
                ('LOTE', models.CharField(blank=True, max_length=15, null=True)),
                ('TIPO', models.CharField(max_length=1)),
                ('SUBTIPO', models.CharField(max_length=1)),
                ('SUBSUBTIPO', models.CharField(max_length=1)),
                ('NATURALEZA', models.CharField(max_length=1)),
                ('CONTABILIZADA', models.CharField(max_length=1)),
                ('FECHA', models.DateTimeField()),
                ('CENTRO_COSTO', models.CharField(blank=True, max_length=25, null=True)),
                ('UNIDAD_DISTRIBUCIO', models.CharField(blank=True, max_length=6, null=True)),
                ('CUENTA_CONTABLE', models.CharField(blank=True, max_length=25, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('ASIENTO_CARDEX', models.CharField(blank=True, max_length=10, null=True)),
                ('DOC_FISCAL', models.CharField(blank=True, max_length=50, null=True)),
                ('TIPO_OPERACION', models.CharField(blank=True, max_length=4, null=True)),
                ('TIPO_PAGO', models.CharField(blank=True, max_length=10, null=True)),
                ('GEN_DOC_ELE', models.CharField(blank=True, max_length=1, null=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
                ('pk', models.CompositePrimaryKey('AUDIT_TRANS_INV', 'CONSECUTIVO', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Transaccion Inv',
                'verbose_name_plural': 'Transaccion Invs',
            },
        ),
    ]
