# Generated by Django 5.2.5 on 2025-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0014_audittransinv_transaccioninv'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioninv',
            name='CANTIDAD',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='transaccioninv',
            name='COSTO_TOT_COMP_DOL',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='transaccioninv',
            name='COSTO_TOT_COMP_LOC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='transaccioninv',
            name='COSTO_TOT_FISC_DOL',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='transaccioninv',
            name='COSTO_TOT_FISC_LOC',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='transaccioninv',
            name='PRECIO_TOTAL_DOLAR',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
        migrations.AddField(
            model_name='transaccioninv',
            name='PRECIO_TOTAL_LOCAL',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=28),
        ),
    ]
