# Generated by Django 5.2.5 on 2025-09-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0015_transaccioninv_cantidad_and_more'),
    ]

    operations = [
        migrations.RunSQL(
        sql="""
        CREATE OR REPLACE VIEW "ims_item_low_stock_view" AS
        WITH LatestOC AS (
            SELECT 
                "ORDEN_COMPRA",
                "ARTICULO",
                "ESTADO",
                "FECHA",
                "FECHA_REQUERIDA",
                ROW_NUMBER() OVER (PARTITION BY "ORDEN_COMPRA" ORDER BY "FECHA" DESC) AS rn
            FROM catalog_management_ordencompralinea
        ),
        LatestEM AS (
            SELECT 
                el."EMBARQUE",
                el."ARTICULO",
                el."CANTIDAD_EMBARCADA",
                e."FECHA_EMBARQUE",
                e."ESTADO",
                el."CreateDate",
                ROW_NUMBER() OVER (PARTITION BY el."EMBARQUE" ORDER BY el."CreateDate" DESC) AS rn
            FROM "catalog_management_embarquelinea" el
            LEFT JOIN "catalog_management_embarque" e
                ON e."EMBARQUE" = el."EMBARQUE"
        )
        SELECT 
            eb."BODEGA",
            eb."ARTICULO",
            a."DESCRIPCION",
            eb."EXISTENCIA_MINIMA",
            eb."PUNTO_DE_REORDEN",
            eb."EXISTENCIA_MAXIMA",
            eb."CANT_DISPONIBLE",
            eb."CANT_RESERVADA",
            eb."CANT_NO_APROBADA",
            eb."CANT_VENCIDA",
            eb."CANT_REMITIDA",
            eb."CANT_TRANSITO",
            eb."CANT_PRODUCCION",
            eb."CANT_PEDIDA",
            eb."CONGELADO",
            eb."BLOQUEA_TRANS",
            LO."ORDEN_COMPRA",
            LE."EMBARQUE",
            (eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO" + eb."CANT_PRODUCCION") AS total_qty,
            LE."CANTIDAD_EMBARCADA" AS "SHIP_QTY",
            LE."FECHA_EMBARQUE" AS "SHIP_DATE",
            LE."ESTADO" AS "SHIP_ESTADO",
            LO."FECHA_REQUERIDA" AS "PO_REQ",
            LO."ESTADO" AS "PO_ESTADO",
            LO."FECHA" AS "PO_SENT"
        FROM "catalog_management_existenciabodega" eb
        JOIN "catalog_management_articulo" a 
            ON eb."ARTICULO" = a."ARTICULO"
        LEFT JOIN LatestOC LO 
            ON eb."ARTICULO" = LO."ARTICULO" AND LO.rn = 1
        LEFT JOIN LatestEM LE 
            ON eb."ARTICULO" = LE."ARTICULO" AND LE.rn = 1
        WHERE eb."PUNTO_DE_REORDEN" IS NOT NULL 
          AND eb."CANT_DISPONIBLE" IS NOT NULL 
          AND eb."PUNTO_DE_REORDEN" > (eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO" + eb."CANT_PRODUCCION")
          and eb."CONGELADO" = 'N';    
        """,
        reverse_sql = "DROP VIEW ims_item_low_stock_view;"
        ),
    ]
