# Generated by Django 5.2.5 on 2025-09-05 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0020_auto_20250905_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowStockView',
            fields=[
                ('ARTICULO', models.CharField(max_length=20)),
                ('BODEGA', models.CharField(max_length=4)),
                ('DESCRIPCION', models.CharField(max_length=254)),
                ('UNIDAD_ALMACEN', models.CharField(max_length=6)),
                ('EXISTENCIA_MINIMA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('EXISTENCIA_MAXIMA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('PUNTO_DE_REORDEN', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_DISPONIBLE', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_RESERVADA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_NO_APROBADA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_VENCIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_TRANSITO', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_PRODUCCION', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_PEDIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CANT_REMITIDA', models.DecimalField(decimal_places=8, max_digits=28)),
                ('CONGELADO', models.CharField(max_length=1)),
                ('BLOQUEA_TRANS', models.CharField(max_length=1)),
                ('ORDEN_COMPRA', models.CharField(max_length=10)),
                ('EMBARQUE', models.CharField(max_length=10)),
                ('total_qty', models.DecimalField(decimal_places=8, max_digits=28)),
                ('SHIP_QTY', models.DecimalField(decimal_places=8, max_digits=28)),
                ('SHIP_DATE', models.DateTimeField(blank=True, null=True)),
                ('SHIP_REQ', models.DateTimeField(blank=True, null=True)),
                ('SHIP_ESTADO', models.CharField(max_length=1)),
                ('PO_QTY', models.DecimalField(decimal_places=8, max_digits=28)),
                ('PO_ESTADO', models.CharField(max_length=1)),
                ('PO_REQ', models.DateTimeField(blank=True, null=True)),
                ('PO_SENT', models.DateTimeField(blank=True, null=True)),
                ('PROVEEDOR', models.CharField(max_length=20)),
                ('PROVEEDOR_NOMBRE', models.CharField(max_length=150)),
                ('PLAZO_REABASTECIMI', models.SmallIntegerField()),
                ('pk', models.CompositePrimaryKey('ARTICULO', 'PROVEEDOR', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ims_item_low_stock_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='RowPointer',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='ordencompralinea',
            name='RowPointer',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
