# Generated by Django 5.2.5 on 2025-09-05 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0021_lowstockview_alter_ordencompra_rowpointer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='RowPointer',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='ordencompralinea',
            name='RowPointer',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
