# Generated by Django 5.2.5 on 2025-09-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0022_alter_ordencompra_rowpointer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetDocumentoEmbarque',
        ),
        migrations.DeleteModel(
            name='DetLinEmbarque',
        ),
        migrations.DeleteModel(
            name='DocumentoEmbarque',
        ),
        migrations.DeleteModel(
            name='EmbarqueDocCp',
        ),
        migrations.DeleteModel(
            name='EmbarqueLinea',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='CLAVE_REFERENCIA_DE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordencompralinea',
            name='TIPO_DESCUENTO_LINEA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ordencompralinea',
            name='TIPO_DESCUENTO_OTRO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
