# Generated by Django 5.2.5 on 2025-09-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0024_detdocumentoembarque_detlinembarque_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguimientoOrden',
        ),
    ]
