# Generated by Django 5.2.5 on 2025-09-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0025_delete_seguimientoorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoOrden',
            fields=[
                ('CONSECUTIVO', models.IntegerField()),
                ('ORDEN_COMPRA', models.CharField(max_length=10)),
                ('ESTADO', models.CharField(max_length=1)),
                ('DESCRIPCION', models.CharField(blank=True, max_length=50, null=True)),
                ('MEDIO', models.CharField(max_length=1)),
                ('FUENTE', models.CharField(blank=True, max_length=25, null=True)),
                ('RowPointer', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Seguimiento Orden',
                'verbose_name_plural': 'Seguimiento Ordens',
            },
        ),
    ]
