# Generated by Django 5.2.5 on 2025-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0026_seguimientoorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosaproboc',
            name='ORDEN_COMPRA',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuariosaproboc',
            name='RowPointer',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
