# Generated by Django 5.2.5 on 2025-09-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0027_alter_usuariosaproboc_orden_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionPago',
            fields=[
                ('CONDICION_PAGO', models.CharField(max_length=4)),
                ('DESCRIPCION', models.CharField(max_length=40)),
                ('DIAS_NETO', models.IntegerField()),
                ('PAGOS_PARCIALES', models.CharField(max_length=1)),
                ('DESCUENTO_CONTADO', models.DecimalField(decimal_places=8, max_digits=28)),
                ('TIPO_CONDPAGO', models.CharField(max_length=2)),
                ('PLAZO_CONDPAGO', models.IntegerField(blank=True, null=True)),
                ('RowPointer', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('TIPO_DIFERIDO', models.CharField(blank=True, max_length=4, null=True)),
                ('USA_DIFERIDO', models.CharField(max_length=1)),
                ('U_METODO_PAGO', models.CharField(blank=True, max_length=100, null=True)),
                ('U_FORMA_PAGO', models.CharField(blank=True, max_length=100, null=True)),
                ('U_PLAZO_PAGO', models.CharField(blank=True, max_length=4, null=True)),
                ('CONDICION_VENTA', models.CharField(blank=True, max_length=2, null=True)),
                ('PLAZO_ES', models.CharField(max_length=4)),
                ('CONDICION_OPERAC_ES', models.CharField(blank=True, max_length=4, null=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
                ('CONDICION_VENTA_OTRO', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'VRA Condicion Pago',
                'verbose_name_plural': 'VRA Condicion Pagos',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MONEDA', models.CharField(max_length=4)),
                ('NOMBRE', models.CharField(max_length=40)),
                ('CODIGO_ISO', models.CharField(blank=True, max_length=4, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
    ]
