# Generated by Django 5.2.5 on 2025-09-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_management', '0030_auto_20250924_0351'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
    DROP VIEW IF EXISTS "ims_item_low_stock_view";
    CREATE OR REPLACE VIEW "ims_item_low_stock_view" AS
    WITH LatestOC AS (
         SELECT 
             "ORDEN_COMPRA",
             "ARTICULO",
             "ESTADO",
             "FECHA",
             "FECHA_REQUERIDA",
             "CANTIDAD_ORDENADA",
             ROW_NUMBER() OVER (PARTITION BY "ARTICULO" ORDER BY "FECHA" DESC) AS rn
         FROM catalog_management_ordencompralinea
     ),
     LatestEM AS (
         SELECT 
             el."EMBARQUE",
             el."ARTICULO",
             el."CANTIDAD_EMBARCADA",
             e."FECHA_EMBARQUE",
             e."FECHA_REQUERIDA",
             e."ESTADO",
             el."CreateDate",
             ROW_NUMBER() OVER (PARTITION BY el."ARTICULO" ORDER BY el."CreateDate" DESC) AS rn
         FROM "catalog_management_embarquelinea" el
         LEFT JOIN "catalog_management_embarque" e
             ON e."EMBARQUE" = el."EMBARQUE"
     ),
     Proveedors as (
          SELECT
              ap."PROVEEDOR",
              ap."ARTICULO",
              p."NOMBRE"
          FROM "catalog_management_articuloproveedor" ap
          LEFT JOIN "catalog_management_proveedor" p
              ON ap."PROVEEDOR" = p."PROVEEDOR"
          WHERE p."CONGELADO" = 'N'
     ),
     LastTrans as (
            SELECT
                ct."FECHA_HORA_TRANSAC",
                ct."AUDIT_TRANS_INV",
                ct."ARTICULO",
                ROW_NUMBER() OVER (PARTITION BY ct."ARTICULO" ORDER BY ct."FECHA_HORA_TRANSAC" DESC) AS rn
            FROM "catalog_management_transaccioninv" ct
            WHERE ct."NATURALEZA" = 'S'
     )
     SELECT 
         eb."BODEGA",
         eb."ARTICULO",
         a."DESCRIPCION",
         a."UNIDAD_ALMACEN",
         eb."EXISTENCIA_MINIMA",
         eb."PUNTO_DE_REORDEN",
         eb."EXISTENCIA_MAXIMA",
         eb."CANT_DISPONIBLE",
         eb."CANT_RESERVADA",
         eb."CANT_NO_APROBADA",
         eb."CANT_VENCIDA",
         eb."CANT_REMITIDA",
         eb."CANT_TRANSITO",
         eb."CANT_PRODUCCION",
         eb."CANT_PEDIDA",
         eb."CONGELADO",
         eb."BLOQUEA_TRANS",
         LO."ORDEN_COMPRA",
         LE."EMBARQUE",
         (eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO" + eb."CANT_PRODUCCION") AS total_qty,
         LE."CANTIDAD_EMBARCADA" AS "SHIP_QTY",
         LE."FECHA_EMBARQUE" AS "SHIP_DATE",
         LE."ESTADO" AS "SHIP_ESTADO",
         LE."FECHA_REQUERIDA" AS "SHIP_REQ",
         LO."FECHA_REQUERIDA" AS "PO_REQ",
         LO."ESTADO" AS "PO_ESTADO",
         LO."FECHA" AS "PO_SENT",
         LO."CANTIDAD_ORDENADA" AS "PO_QTY",
         P."PROVEEDOR",
         P."NOMBRE" AS "PROVEEDOR_NOMBRE",
         LT."FECHA_HORA_TRANSAC" as "LAST_TRANSACTION",
         LT."AUDIT_TRANS_INV" as "LAST_TRANSACTION_ID"
     FROM "catalog_management_existenciabodega" eb
     JOIN "catalog_management_articulo" a 
         ON eb."ARTICULO" = a."ARTICULO"
     LEFT JOIN LatestOC LO 
         ON eb."ARTICULO" = LO."ARTICULO" AND LO.rn = 1
     LEFT JOIN LatestEM LE 
         ON eb."ARTICULO" = LE."ARTICULO" AND LE.rn = 1
     LEFT JOIN Proveedors P 
         ON eb."ARTICULO" = P."ARTICULO" 
     LEFT JOIN LastTrans LT 
         ON eb."ARTICULO" = LT."ARTICULO" AND LT.rn = 1 
     WHERE eb."PUNTO_DE_REORDEN" IS NOT NULL 
       AND eb."CANT_DISPONIBLE" IS NOT NULL 
       AND eb."PUNTO_DE_REORDEN" > (eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO" + eb."CANT_PRODUCCION");    
     """,
            reverse_sql="DROP VIEW ims_item_low_stock_view;"
        ),
    ]
