# Generated by Django 5.2.5 on 2025-10-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0032_auto_20251003_0249"),
    ]

    operations = [
        migrations.CreateModel(
            name="Localizacion",
            fields=[
                ("BODEGA", models.CharField(max_length=4)),
                ("LOCALIZACION", models.CharField(max_length=8)),
                ("DESCRIPCION", models.CharField(max_length=40)),
                (
                    "VOLUMEN",
                    models.DecimalField(decimal_places=8, default=0.0, max_digits=28),
                ),
                (
                    "PESO_MAXIMO",
                    models.DecimalField(decimal_places=8, default=0.0, max_digits=28),
                ),
                (
                    "RowPointer",
                    models.CharField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Localizacion",
                "verbose_name_plural": "Localizaciones",
            },
        ),
    ]
