# Generated by Django 5.2.5 on 2025-10-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0034_auto_20251009_0752"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizacion",
            name="RowPointer",
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
