# Generated by Django 5.2.5 on 2025-11-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0035_alter_localizacion_rowpointer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteConfig",
            fields=[
                ("AJUSTE_CONFIG", models.CharField(max_length=4)),
                ("DESCRIPCION", models.CharField(max_length=15)),
                ("AJUSTE_BASE", models.CharField(max_length=1)),
                ("ACTIVA", models.CharField(max_length=1)),
                ("INGRESO", models.CharField(max_length=1)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("GEN_DOC_ELE", models.CharField(blank=True, max_length=1, null=True)),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Ajuste Config",
                "verbose_name_plural": "Ajuste Configs",
            },
        ),
        migrations.CreateModel(
            name="AjusteSubsubtipo",
            fields=[
                ("AJUSTE_CONFIG", models.CharField(max_length=4)),
                ("SUBSUBTIPO", models.CharField(max_length=1)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Ajuste Subsubtipo",
                "verbose_name_plural": "Ajuste Subsubtipos",
            },
        ),
        migrations.CreateModel(
            name="AjusteSubtipo",
            fields=[
                ("AJUSTE_CONFIG", models.CharField(max_length=4)),
                ("SUBTIPO", models.CharField(max_length=1)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Ajuste Subtipo",
                "verbose_name_plural": "Ajuste Subtipos",
            },
        ),
        migrations.CreateModel(
            name="ConsecutivoCi",
            fields=[
                ("CONSECUTIVO", models.CharField(max_length=10)),
                ("ULTIMO_USUARIO", models.CharField(max_length=50)),
                ("DESCRIPCION", models.CharField(max_length=40)),
                ("MASCARA", models.CharField(max_length=50)),
                ("SIGUIENTE_CONSEC", models.CharField(max_length=50)),
                ("EDITABLE", models.CharField(max_length=1)),
                ("MULTIPLES_TRANS", models.CharField(max_length=1)),
                (
                    "FORMATO_IMP",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("ULT_FECHA_HORA", models.DateTimeField()),
                ("TODAS_TRANS", models.CharField(max_length=1)),
                ("TIPO", models.CharField(max_length=4)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("U_PAQ_DEST", models.CharField(blank=True, max_length=4, null=True)),
                ("USA_TRASLADO", models.CharField(max_length=1)),
                ("EMAIL_CFDI", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "TIENE_COMPLEMENTO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Consecutivo Ci",
                "verbose_name_plural": "Consecutivo Cis",
            },
        ),
        migrations.CreateModel(
            name="DocumentoInv",
            fields=[
                ("PAQUETE_INVENTARIO", models.CharField(max_length=4)),
                ("DOCUMENTO_INV", models.CharField(max_length=50)),
                ("CONSECUTIVO", models.CharField(blank=True, max_length=10, null=True)),
                ("REFERENCIA", models.CharField(max_length=200)),
                ("FECHA_HOR_CREACION", models.DateTimeField()),
                ("FECHA_DOCUMENTO", models.DateTimeField()),
                ("SELECCIONADO", models.CharField(max_length=1)),
                ("USUARIO", models.CharField(max_length=50)),
                ("MENSAJE_SISTEMA", models.TextField(blank=True, null=True)),
                (
                    "USUARIO_APRO",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("FECHA_HORA_APROB", models.DateTimeField(blank=True, null=True)),
                ("APROBADO", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Documento Inv",
                "verbose_name_plural": "Documento Invs",
            },
        ),
        migrations.CreateModel(
            name="LineaDocInv",
            fields=[
                ("PAQUETE_INVENTARIO", models.CharField(max_length=4)),
                ("DOCUMENTO_INV", models.CharField(max_length=50)),
                ("LINEA_DOC_INV", models.IntegerField()),
                ("AJUSTE_CONFIG", models.CharField(max_length=4)),
                ("NIT", models.CharField(blank=True, max_length=20, null=True)),
                ("ARTICULO", models.CharField(max_length=20)),
                ("BODEGA", models.CharField(blank=True, max_length=4, null=True)),
                ("LOCALIZACION", models.CharField(blank=True, max_length=8, null=True)),
                ("LOTE", models.CharField(blank=True, max_length=15, null=True)),
                ("TIPO", models.CharField(max_length=1)),
                ("SUBTIPO", models.CharField(max_length=1)),
                ("SUBSUBTIPO", models.CharField(max_length=1)),
                ("CANTIDAD", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "COSTO_TOTAL_LOCAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_TOTAL_DOLAR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "PRECIO_TOTAL_LOCAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "PRECIO_TOTAL_DOLAR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "BODEGA_DESTINO",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "LOCALIZACION_DEST",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "CENTRO_COSTO",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("SECUENCIA", models.DateTimeField(blank=True, null=True)),
                ("SERIE_CADENA", models.IntegerField(blank=True, null=True)),
                (
                    "UNIDAD_DISTRIBUCIO",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "CUENTA_CONTABLE",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "COSTO_TOTAL_LOCAL_COMP",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_TOTAL_DOLAR_COMP",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("CAI", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "TIPO_OPERACION",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("TIPO_PAGO", models.CharField(blank=True, max_length=10, null=True)),
                ("GEN_DOC_ELE", models.CharField(blank=True, max_length=1, null=True)),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Linea Doc Inv",
                "verbose_name_plural": "Linea Doc Invs",
            },
        ),
        migrations.CreateModel(
            name="PaqueteInventario",
            fields=[
                ("PAQUETE_INVENTARIO", models.CharField(max_length=4)),
                ("DESCRIPCION", models.CharField(max_length=40)),
                ("ULTIMO_USUARIO", models.CharField(max_length=50)),
                ("USUARIO_CREADOR", models.CharField(max_length=50)),
                ("FECHA_ULT_ACCESO", models.DateTimeField()),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Paquete Inventario",
                "verbose_name_plural": "Paquete Inventarios",
            },
        ),
        migrations.AlterModelOptions(
            name="condicionpago",
            options={
                "verbose_name": "Condicion Pago",
                "verbose_name_plural": "Condicion Pagos",
            },
        ),
    ]
