# Generated by Django 5.2.5 on 2025-11-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog_management",
            "0036_ajusteconfig_ajustesubsubtipo_ajustesubtipo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExistenciaReserva",
            fields=[
                ("ARTICULO", models.CharField(max_length=20)),
                ("APLICACION", models.CharField(max_length=60)),
                ("BODEGA", models.CharField(max_length=4)),
                ("LOTE", models.CharField(max_length=15)),
                ("LOCALIZACION", models.CharField(max_length=8)),
                ("SERIE_CADENA", models.IntegerField(blank=True, null=True)),
                ("MODULO_ORIGEN", models.CharField(max_length=4)),
                ("CANTIDAD", models.DecimalField(decimal_places=8, max_digits=28)),
                ("USUARIO", models.CharField(max_length=50)),
                ("FECHA_HORA", models.DateTimeField()),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Existencia Reserva",
                "verbose_name_plural": "Existencia Reservas",
            },
        ),
    ]
