# Generated by Django 5.2.5 on 2025-11-17 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_management", "0037_existenciareserva"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
    DROP MATERIALIZED VIEW IF EXISTS "ims_item_low_stock_view";
    CREATE MATERIALIZED VIEW "ims_item_low_stock_view" AS
    WITH LatestOC AS (
         SELECT 
             ocl."ORDEN_COMPRA",
             ocl."ARTICULO",
             ocl."ESTADO",
             ocl."FECHA",
             ocl."FECHA_REQUERIDA",
             ocl."CANTIDAD_ORDENADA",
             oc."FECHA_HORA_CONFIR",
             oc."PROVEEDOR",
             oc."FECHA_EMISION",
             ROW_NUMBER() OVER (PARTITION BY ocl."ARTICULO" ORDER BY ocl."CreateDate" DESC) AS rn
         FROM catalog_management_ordencompralinea ocl
         LEFT JOIN catalog_management_ordencompra oc
                ON oc."ORDEN_COMPRA" = ocl."ORDEN_COMPRA"
     ),
     LatestEM AS (
          SELECT 
             el."EMBARQUE",
             el."ARTICULO",
             el."CANTIDAD_EMBARCADA",
             e."FECHA_EMBARQUE",
             e."FECHA_REQUERIDA",
             e."ESTADO",
             loc."FECHA_EMISION",
             loc."ORDEN_COMPRA",
             e."FECHA_CRM",
             e."FECHA_PLANTA",
             loc."FECHA_HORA_CONFIR",
             loc."PROVEEDOR",
             ROW_NUMBER() OVER (PARTITION BY el."ARTICULO" ORDER BY el."CreateDate" DESC) AS rn
         FROM "catalog_management_embarquelinea" el
         LEFT JOIN "catalog_management_embarque" e
             ON e."EMBARQUE" = el."EMBARQUE"
         LEFT JOIN LatestOC loc
             ON el."ORDEN_COMPRA" = loc."ORDEN_COMPRA" AND el."ARTICULO" = loc."ARTICULO"
     ),
     Proveedors as (
          SELECT
              ap."PROVEEDOR",
              ap."ARTICULO",
              p."NOMBRE",
              p."PAIS"
          FROM "catalog_management_articuloproveedor" ap
          LEFT JOIN "catalog_management_proveedor" p
              ON ap."PROVEEDOR" = p."PROVEEDOR"
          WHERE p."CONGELADO" = 'N'
     ),
     LastTrans as (
            SELECT
                ct."FECHA_HORA_TRANSAC",
                ct."AUDIT_TRANS_INV",
                ct."ARTICULO",
                ROW_NUMBER() OVER (PARTITION BY ct."ARTICULO" ORDER BY ct."FECHA_HORA_TRANSAC" DESC) AS rn
            FROM "catalog_management_transaccioninv" ct
            WHERE ct."NATURALEZA" = 'S'
     )
     SELECT 
         eb."BODEGA",
         eb."ARTICULO",
         a."DESCRIPCION",
         a."UNIDAD_ALMACEN",
         eb."EXISTENCIA_MINIMA",
         eb."PUNTO_DE_REORDEN",
         eb."EXISTENCIA_MAXIMA",
         eb."CANT_DISPONIBLE",
         eb."CANT_RESERVADA",
         eb."CANT_NO_APROBADA",
         eb."CANT_VENCIDA",
         eb."CANT_REMITIDA",
         eb."CANT_TRANSITO",
         eb."CANT_PRODUCCION",
         eb."CANT_PEDIDA",
         eb."CONGELADO",
         eb."BLOQUEA_TRANS",
         (eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO") AS total_qty,
         ROUND(((eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO")/eb."PUNTO_DE_REORDEN")*100, 3) AS AVAILABILITY_PERC,
         LE."EMBARQUE",
         LE."CANTIDAD_EMBARCADA" AS "SHIP_QTY",
         LE."FECHA_EMBARQUE" AS "SHIP_DATE",
         LE."ESTADO" AS "SHIP_ESTADO",
         LE."FECHA_REQUERIDA" AS "SHIP_REQ",
         LO."ORDEN_COMPRA",
         LO."FECHA_REQUERIDA" AS "PO_REQ",
         LO."ESTADO" AS "PO_ESTADO",
         LO."FECHA" AS "PO_SENT",
         LO."CANTIDAD_ORDENADA" AS "PO_QTY",
         LE."FECHA_EMISION" AS "SHIP_EMISION",
         LE."FECHA_HORA_CONFIR" AS "SHIP_CONFIR",
         LE."FECHA_CRM" AS "SHIP_CRM",
         LE."FECHA_PLANTA" AS "SHIP_PLANTA",
         P."PROVEEDOR",
         P."NOMBRE" AS "PROVEEDOR_NOMBRE",
         p."PAIS" AS "PROVEEDOR_PAIS",
         LT."FECHA_HORA_TRANSAC" AS "LAST_TRANSACTION",
         LT."AUDIT_TRANS_INV" AS "LAST_TRANSACTION_ID"
     FROM "catalog_management_existenciabodega" eb
     JOIN "catalog_management_articulo" a 
         ON eb."ARTICULO" = a."ARTICULO"
     INNER JOIN Proveedors P 
         ON eb."ARTICULO" = P."ARTICULO" 
     LEFT JOIN LatestOC LO 
         ON eb."ARTICULO" = LO."ARTICULO" AND LO."PROVEEDOR" = P."PROVEEDOR" AND LO.rn = 1 
     LEFT JOIN LatestEM LE 
         ON eb."ARTICULO" = LE."ARTICULO" AND LE."PROVEEDOR" = P."PROVEEDOR" AND LE.rn = 1 
     LEFT JOIN LastTrans LT 
         ON eb."ARTICULO" = LT."ARTICULO" AND LT.rn = 1 
     WHERE eb."PUNTO_DE_REORDEN" IS NOT NULL 
       AND eb."CANT_DISPONIBLE" IS NOT NULL 
       AND eb."PUNTO_DE_REORDEN" > (eb."CANT_DISPONIBLE" + eb."CANT_TRANSITO");     
    """,
            reverse_sql="DROP MATERIALIZED VIEW ims_item_low_stock_view;"
        )

    ]
