# Generated by Django 5.2.5 on 2025-11-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0038_auto_20251117_0257"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoletaInvFisico",
            fields=[
                ("BOLETA", models.CharField(max_length=8)),
                ("ARTICULO", models.CharField(max_length=20)),
                ("BODEGA", models.CharField(max_length=4)),
                ("LOCALIZACION", models.CharField(blank=True, max_length=8, null=True)),
                ("LOTE", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "CANT_DISP_RESERV",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_NO_APROBADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("CANT_VENCIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("USUARIO", models.CharField(max_length=50)),
                ("FECHA_HORA", models.DateTimeField()),
                ("VALIDADA", models.CharField(max_length=1)),
                ("SERIE_CADENA_DISP", models.IntegerField(blank=True, null=True)),
                ("SERIE_CADENA_NOAPR", models.IntegerField(blank=True, null=True)),
                ("SERIE_CADENA_VENC", models.IntegerField(blank=True, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Boleta Inv Fisico",
                "verbose_name_plural": "Boleta Inv Fisicos",
            },
        ),
        migrations.CreateModel(
            name="ExistenciaCierre",
            fields=[
                ("FECHA_CIERRE", models.DateTimeField()),
                ("ARTICULO", models.CharField(max_length=20)),
                ("TIPO_COSTO", models.CharField(max_length=1)),
                ("TIPO_FECHA", models.CharField(max_length=1)),
                ("BODEGA", models.CharField(max_length=4)),
                (
                    "COSTO_FISC_UNT_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_FISC_UNT_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_COMP_UNT_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_COMP_UNT_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_DISPONIBLE",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_RESERVADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_NO_APROBADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("CANT_VENCIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("CANT_REMITIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Existencia Cierre",
                "verbose_name_plural": "Existencia Cierres",
            },
        ),
    ]
