# Generated by Django 5.2.5 on 2025-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0040_auto_20251125_0217"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAuditView",
            fields=[
                ("FECHA_CIERRE", models.DateTimeField()),
                ("ARTICULO", models.CharField(max_length=20)),
                ("BODEGA", models.CharField(max_length=4)),
                (
                    "current_disponible",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_reservada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_no_aprobada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_vencida",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_remitida",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "snap_disponible",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "snap_reservada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "snap_no_aprobada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("snap_vencida", models.DecimalField(decimal_places=8, max_digits=28)),
                ("snap_remitida", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "diff_disponible",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_reservada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_no_aprobada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("diff_vencida", models.DecimalField(decimal_places=8, max_digits=28)),
                ("diff_remitida", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "COSTO_COMP_UNT_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_COMP_UNT_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_UNT_PROMEDIO_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_UNT_PROMEDIO_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_costo_comp_loc",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_costo_comp_dol",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("current_record_date", models.DateTimeField()),
                ("snapshot_record_date", models.DateTimeField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "ARTICULO",
                        "BODEGA",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "ims_inventory_audit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExistenciaLoteCierre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("FECHA_CIERRE", models.DateTimeField()),
                ("BODEGA", models.CharField(max_length=4)),
                ("ARTICULO", models.CharField(max_length=20)),
                ("LOCALIZACION", models.CharField(max_length=8)),
                ("LOTE", models.CharField(max_length=15)),
                ("TIPO_FECHA", models.CharField(max_length=1)),
                (
                    "COSTO_FISC_UNT_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_FISC_UNT_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_COMP_UNT_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_COMP_UNT_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_DISPONIBLE",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_RESERVADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_NO_APROBADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("CANT_VENCIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("CANT_REMITIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("RecordDate", models.DateTimeField(auto_now=True)),
                ("CreateDate", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Existencia Lote Cierre",
                "verbose_name_plural": "Existencia Lote Cierres",
            },
        ),
    ]
