# Generated by Django 5.2.5 on 2025-11-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0042_auto_20251125_0525"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAuditLoteView",
            fields=[
                ("FECHA_CIERRE", models.DateTimeField()),
                ("ARTICULO", models.CharField(max_length=20)),
                ("BODEGA", models.CharField(max_length=4)),
                ("LOCALIZACION", models.CharField(max_length=8)),
                ("LOTE", models.CharField(max_length=15)),
                (
                    "current_disponible",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_reservada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_no_aprobada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_vencida",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "current_remitida",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "snap_disponible",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "snap_reservada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "snap_no_aprobada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("snap_vencida", models.DecimalField(decimal_places=8, max_digits=28)),
                ("snap_remitida", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "diff_disponible",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_reservada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_no_aprobada",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("diff_vencida", models.DecimalField(decimal_places=8, max_digits=28)),
                ("diff_remitida", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "COSTO_COMP_UNT_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_COMP_UNT_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_UNT_PROMEDIO_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_UNT_PROMEDIO_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_costo_comp_loc",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "diff_costo_comp_dol",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("current_record_date", models.DateTimeField()),
                ("snapshot_record_date", models.DateTimeField()),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "ARTICULO",
                        "BODEGA",
                        "LOCALIZACION",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "ims_inventory_lote_audit",
                "managed": False,
            },
        ),
    ]
