# Generated by Django 5.2.5 on 2025-12-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0043_inventoryauditloteview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                ("TIPO_DOCUMENTO", models.CharField(max_length=1)),
                ("FACTURA", models.CharField(max_length=50)),
                ("AUDIT_TRANS_INV", models.IntegerField(blank=True, null=True)),
                ("ESTA_DESPACHADO", models.CharField(max_length=1)),
                ("EN_INVESTIGACION", models.CharField(max_length=1)),
                ("TRANS_ADICIONALES", models.CharField(max_length=1)),
                ("ESTADO_REMISION", models.CharField(max_length=1)),
                (
                    "ASIENTO_DOCUMENTO",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "DESCUENTO_VOLUMEN",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("MONEDA_FACTURA", models.CharField(max_length=1)),
                (
                    "COMENTARIO_CXC",
                    models.CharField(blank=True, max_length=249, null=True),
                ),
                ("FECHA_DESPACHO", models.DateTimeField()),
                ("CLASE_DOCUMENTO", models.CharField(max_length=1)),
                ("FECHA_RECIBIDO", models.DateTimeField()),
                ("PEDIDO", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "FACTURA_ORIGINAL",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "TIPO_ORIGINAL",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "COMISION_COBRADOR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TARJETA_CREDITO",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("TOTAL_VOLUMEN", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "NUMERO_AUTORIZA",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("TOTAL_PESO", models.DecimalField(decimal_places=8, max_digits=28)),
                ("MONTO_COBRADO", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "TOTAL_IMPUESTO1",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("FECHA", models.DateTimeField()),
                ("FECHA_ENTREGA", models.DateTimeField()),
                (
                    "TOTAL_IMPUESTO2",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "PORC_DESCUENTO2",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("MONTO_FLETE", models.DecimalField(decimal_places=8, max_digits=28)),
                ("MONTO_SEGURO", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "MONTO_DOCUMENTACIO",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("TIPO_DESCUENTO1", models.CharField(max_length=1)),
                ("TIPO_DESCUENTO2", models.CharField(max_length=1)),
                (
                    "MONTO_DESCUENTO1",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "MONTO_DESCUENTO2",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "PORC_DESCUENTO1",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("TOTAL_FACTURA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("FECHA_PEDIDO", models.DateTimeField()),
                ("FECHA_HORA_ANULA", models.DateTimeField(blank=True, null=True)),
                ("FECHA_ORDEN", models.DateTimeField(blank=True, null=True)),
                (
                    "TOTAL_MERCADERIA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COMISION_VENDEDOR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "ORDEN_COMPRA",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("FECHA_HORA", models.DateTimeField()),
                (
                    "TOTAL_UNIDADES",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("NUMERO_PAGINAS", models.SmallIntegerField()),
                ("TIPO_CAMBIO", models.DecimalField(decimal_places=8, max_digits=28)),
                ("ANULADA", models.CharField(max_length=1)),
                ("MODULO", models.CharField(max_length=4)),
                ("CARGADO_CG", models.CharField(max_length=1)),
                ("CARGADO_CXC", models.CharField(max_length=1)),
                ("EMBARCAR_A", models.CharField(blank=True, max_length=160, null=True)),
                (
                    "DIREC_EMBARQUE",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "DIRECCION_FACTURA",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("MULTIPLICADOR_EV", models.SmallIntegerField()),
                ("OBSERVACIONES", models.TextField(blank=True, null=True)),
                ("RUBRO1", models.CharField(blank=True, max_length=50, null=True)),
                ("RUBRO2", models.CharField(blank=True, max_length=50, null=True)),
                ("RUBRO3", models.CharField(blank=True, max_length=50, null=True)),
                ("RUBRO4", models.CharField(blank=True, max_length=50, null=True)),
                ("RUBRO5", models.CharField(blank=True, max_length=50, null=True)),
                ("VERSION_NP", models.IntegerField()),
                ("MONEDA", models.CharField(max_length=1)),
                ("NIVEL_PRECIO", models.CharField(max_length=12)),
                ("COBRADOR", models.CharField(max_length=4)),
                ("RUTA", models.CharField(max_length=4)),
                ("USUARIO", models.CharField(max_length=50)),
                (
                    "USUARIO_ANULA",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("CONDICION_PAGO", models.CharField(max_length=4)),
                ("ZONA", models.CharField(max_length=4)),
                ("VENDEDOR", models.CharField(max_length=4)),
                (
                    "DOC_CREDITO_CXC",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("CLIENTE_DIRECCION", models.CharField(max_length=20)),
                ("CLIENTE_CORPORAC", models.CharField(max_length=20)),
                ("CLIENTE_ORIGEN", models.CharField(max_length=20)),
                ("CLIENTE", models.CharField(max_length=20)),
                ("PAIS", models.CharField(max_length=4)),
                ("SUBTIPO_DOC_CXC", models.SmallIntegerField(blank=True, null=True)),
                (
                    "TIPO_CREDITO_CXC",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("TIPO_DOC_CXC", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "MONTO_ANTICIPO",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "TOTAL_PESO_NETO",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("FECHA_RIGE", models.DateTimeField()),
                ("CONTRATO", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "PORC_INTCTE",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("USA_DESPACHOS", models.CharField(max_length=1)),
                ("COBRADA", models.CharField(max_length=1)),
                ("DESCUENTO_CASCADA", models.CharField(max_length=1)),
                (
                    "DIRECCION_EMBARQUE",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("CONSECUTIVO", models.CharField(blank=True, max_length=10, null=True)),
                ("REIMPRESO", models.IntegerField()),
                (
                    "DIVISION_GEOGRAFICA1",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "DIVISION_GEOGRAFICA2",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "BASE_IMPUESTO1",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "BASE_IMPUESTO2",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "NOMBRE_CLIENTE",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("DOC_FISCAL", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "NOMBREMAQUINA",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "SERIE_RESOLUCION",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("CONSEC_RESOLUCION", models.IntegerField(blank=True, null=True)),
                ("GENERA_DOC_FE", models.CharField(max_length=1)),
                (
                    "TASA_IMPOSITIVA",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "TASA_IMPOSITIVA_PORC",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("TASA_CREE1", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "TASA_CREE1_PORC",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("TASA_CREE2", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "TASA_CREE2_PORC",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "TASA_GAN_OCASIONAL_PORC",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("CONTRATO_AC", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "AJUSTE_REDONDEO",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("U_REF_PROY", models.CharField(blank=True, max_length=7, null=True)),
                ("U_TIPO_VENTA", models.CharField(max_length=9)),
                ("USO_CFDI", models.CharField(blank=True, max_length=3, null=True)),
                ("FORMA_PAGO", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "CLAVE_REFERENCIA_DE",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("FECHA_REFERENCIA_DE", models.DateTimeField(blank=True, null=True)),
                (
                    "JUSTI_DEV_HACIEND",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "TIPO_OPERACION",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("INCOTERMS", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "U_AD_WM_NUMERO_VENDEDOR",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                (
                    "U_AD_WM_ENVIAR_GLN",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "U_AD_WM_NUMERO_RECEPCION",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_WM_NUMERO_RECLAMO",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "U_AD_WM_FECHA_RECLAMO",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_PC_NUMERO_VENDEDOR",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "U_AD_PC_ENVIAR_GLN",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "U_AD_GS_NUMERO_VENDEDOR",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "U_AD_GS_ENVIAR_GLN",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "U_AD_GS_NUMERO_RECEPCION",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_GS_FECHA_RECEPCION",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_AM_NUMERO_PROVEEDOR",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "U_AD_AM_ENVIAR_GLN",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                (
                    "U_AD_AM_NUMERO_RECEPCION",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_AM_NUMERO_RECLAMO",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "U_AD_AM_FECHA_RECLAMO",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_AM_FECHA_RECEPCION",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "U_AD_CC_REMISION",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("U_AD_CC_FECHA_CONSUMO", models.DateField(blank=True, null=True)),
                (
                    "U_AD_CC_HOJA_ENTRADA",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("CLAVE_DE", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ACTIVIDAD_COMERCIAL",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "MONTO_OTRO_CARGO",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "MONTO_TOTAL_IVA_DEVUELTO",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "CODIGO_REFERENCIA_DE",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "TIPO_REFERENCIA_DE",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("CANCELACION", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "ESTADO_CANCELACION",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "TIENE_RELACIONADOS",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("PREFIJO", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "FECHA_INICIO_RESOLUCION",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("FECHA_FINAL_RESOLUCION", models.DateTimeField(blank=True, null=True)),
                (
                    "CLAVE_TECNICA",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("MATRICULA_MERCANTIL", models.IntegerField(blank=True, null=True)),
                (
                    "ES_FACTURA_REEMPLAZO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "FACTURA_ORIGINAL_REEMPLAZO",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "CONSECUTIVO_FTC",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("NUMERO_FTC", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "NIT_TRANSPORTADOR",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "NCF_MODIFICADO",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "NUM_OC_EXENTA",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "NUM_CONS_REG_EXO",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "NUM_IRSEDE_AGR_GAN",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "U_AD_WM_TIPO_NC",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "CUENTA_ASIENTO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("TIPO_PAGO", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "TIPO_DESCUENTO_GLOBAL",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "TIPO_FACTURA",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("TIPO_NC", models.CharField(blank=True, max_length=2, null=True)),
                ("TIPO_DETRAC", models.CharField(blank=True, max_length=4, null=True)),
                ("ACT_DETRAC", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "PORC_DETRAC",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "GUUID_ORIGINAL",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "TIENE_COMPLEMENTO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "GENERAR_CFDI_TRASLADO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("EXPORTACION", models.CharField(max_length=2)),
                (
                    "TIPO_RELACION",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "MOTIVO_CANCELACION",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "FOLIO_FISCAL_SUSTITUTO",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("CUFE", models.CharField(blank=True, max_length=100, null=True)),
                ("CODIGOQR", models.TextField(blank=True, null=True)),
                (
                    "TIPO_MODIFICACION",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "RAZON_MODIFICACION",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("TIPO_NCF_ECF", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "CONTRIBUYENTE",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("TIPO_INGRESO", models.CharField(blank=True, max_length=2, null=True)),
                ("TIPO_PAGO_RD", models.CharField(blank=True, max_length=1, null=True)),
                ("TOPE_FC", models.CharField(blank=True, max_length=1, null=True)),
                ("DTE", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "CODIGO_GENERACION",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ESTADO_COMPROBANTE",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "SELLO_RECEPCION",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "MASCARA_DTE",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "TIPO_INVALIDACION",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "RECINTO_FISCAL",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "TITULO_REMISION",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("TIPO_ITEM_ES", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "REGIMEN_EXP_ES",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("GENERA_GUIA_REMISION", models.CharField(max_length=1)),
                (
                    "PROCEDENCIA_PEDIDO",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
        migrations.CreateModel(
            name="FacturaLinea",
            fields=[
                ("FACTURA", models.CharField(max_length=50)),
                ("TIPO_DOCUMENTO", models.CharField(max_length=1)),
                ("LINEA", models.SmallIntegerField()),
                ("BODEGA", models.CharField(max_length=4)),
                (
                    "COSTO_TOTAL_DOLAR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("PEDIDO", models.CharField(blank=True, max_length=50, null=True)),
                ("ARTICULO", models.CharField(max_length=20)),
                ("LOCALIZACION", models.CharField(blank=True, max_length=8, null=True)),
                ("LOTE", models.CharField(blank=True, max_length=15, null=True)),
                ("ANULADA", models.CharField(max_length=1)),
                ("FECHA_FACTURA", models.DateTimeField()),
                ("CANTIDAD", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "PRECIO_UNITARIO",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TOTAL_IMPUESTO1",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TOTAL_IMPUESTO2",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "DESC_TOT_LINEA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "DESC_TOT_GENERAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("COSTO_TOTAL", models.DecimalField(decimal_places=8, max_digits=28)),
                ("PRECIO_TOTAL", models.DecimalField(decimal_places=8, max_digits=28)),
                ("DESCRIPCION", models.TextField(blank=True, null=True)),
                ("COMENTARIO", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "CANTIDAD_DEVUELT",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "DESCUENTO_VOLUMEN",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("TIPO_LINEA", models.CharField(max_length=1)),
                (
                    "CANTIDAD_ACEPTADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_NO_ENTREGADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_TOTAL_LOCAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("PEDIDO_LINEA", models.SmallIntegerField(blank=True, null=True)),
                ("MULTIPLICADOR_EV", models.SmallIntegerField()),
                ("SERIE_CADENA", models.IntegerField(blank=True, null=True)),
                ("SERIE_CAD_NO_ACEPT", models.IntegerField(blank=True, null=True)),
                ("SERIE_CAD_ACEPTADA", models.IntegerField(blank=True, null=True)),
                (
                    "DOCUMENTO_ORIGEN",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("LINEA_ORIGEN", models.SmallIntegerField(blank=True, null=True)),
                ("TIPO_ORIGEN", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "UNIDAD_DISTRIBUCIO",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "CANT_DESPACHADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_ESTIM_LOCAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_ESTIM_DOLAR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_ANUL_PORDESPA",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "MONTO_RETENCION",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "BASE_IMPUESTO1",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "BASE_IMPUESTO2",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("PROYECTO", models.CharField(blank=True, max_length=25, null=True)),
                ("FASE", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "CENTRO_COSTO",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "CUENTA_CONTABLE",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "COSTO_TOTAL_COMP",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_TOTAL_COMP_LOCAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_TOTAL_COMP_DOLAR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_ESTIM_COMP_LOCAL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "COSTO_ESTIM_COMP_DOLAR",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_DEV_PROCESO",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TIPO_IMPUESTO1",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("TIPO_TARIFA1", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "TIPO_IMPUESTO2",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("TIPO_TARIFA2", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "PORC_EXONERACION",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "MONTO_EXONERACION",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "ES_OTRO_CARGO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "ES_CANASTA_BASICA",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "ES_SERVICIO_MEDICO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "MONTO_DEVUELTO_IVA",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "PORC_EXONERACION2",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "MONTO_EXONERACION2",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "TIPO_DESCUENTO_LINEA",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "CODIGO_IMPUESTO",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "INDICADOR_FACTURACION",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "TIPO_IMP_ADIC",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "PORC_IMP1",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "PORC_IMP2",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "BIEN_SERVICIO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "TIPO_DESCUENTO",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "TIPO_DESC_GENERAL",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "PORC_DESC_LIN",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "PORC_DESC_GEN",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "PRECIO_BASE_LOCAL_ES",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "DIFERENCIAL_ES",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "ADVALOREM_ES",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Factura Linea",
                "verbose_name_plural": "Factura Lineas",
            },
        ),
    ]
