# Generated by Django 5.2.5 on 2025-12-01 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_management", "0044_factura_facturalinea"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
        DROP MATERIALIZED VIEW IF EXISTS "ims_items_sales_history";
        CREATE MATERIALIZED VIEW "ims_items_sales_history" AS
        SELECT
          d."ARTICULO"                          AS "ARTICULO",
          (COALESCE(f."FECHA", d."FECHA_FACTURA")::date) AS "DS",
          SUM(d."CANTIDAD")                     AS "Y",
          SUM(d."PRECIO_TOTAL")                 AS "SALES_AMOUNT"
        FROM catalog_management_facturalinea d
        JOIN catalog_management_factura f
          ON f."FACTURA" = d."FACTURA"
          AND f."TIPO_DOCUMENTO" = d."TIPO_DOCUMENTO"
        WHERE
          -- only last 2 years (relative to CURRENT_DATE)
          COALESCE(f."FECHA", d."FECHA_FACTURA")::date >= (CURRENT_DATE - INTERVAL '2 years')
          -- ignore obviously cancelled headers/lines (attempt to cover common values)
          AND COALESCE(UPPER(f."ANULADA"), 'N') NOT IN ('S')
          AND COALESCE(UPPER(d."ANULADA"), 'N') NOT IN ('S')
          -- ignore zero or negative quantities (adjust if you want returns included)
          AND COALESCE(d."CANTIDAD", 0) > 0
        GROUP BY d."ARTICULO", (COALESCE(f."FECHA", d."FECHA_FACTURA")::date);    
    """,
            reverse_sql="DROP MATERIALIZED VIEW ims_items_sales_history;"
        )
    ]
