# Generated by Django 5.2.5 on 2025-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0046_auto_20251202_0327"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemsSalesHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ARTICULO", models.CharField(max_length=20)),
                ("DS", models.DateField()),
                ("Y", models.DecimalField(decimal_places=8, max_digits=28)),
                ("SALES_AMOUNT", models.DecimalField(decimal_places=8, max_digits=28)),
            ],
            options={
                "db_table": "ims_items_sales_history",
                "managed": False,
            },
        ),
    ]
