# Generated by Django 5.2.5 on 2025-12-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0047_itemssaleshistory"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE VIEW "ims_item_master_view" AS
                SELECT 
                    eb."BODEGA",
                    eb."ARTICULO",
                    a."DESCRIPCION",
                    eb."EXISTENCIA_MINIMA",
                    a."UNIDAD_ALMACEN",
                    a."UNIDAD_EMPAQUE",
                    a."UNIDAD_VENTA",
                    eb."PUNTO_DE_REORDEN",
                    eb."EXISTENCIA_MAXIMA",
                    eb."CANT_DISPONIBLE",
                    eb."CANT_RESERVADA",
                    eb."CANT_NO_APROBADA",
                    eb."CANT_VENCIDA",
                    eb."CANT_REMITIDA",
                    a."CODIGO_BARRAS_INVT",
                    a."CODIGO_BARRAS_VENT",
                    eb."CANT_TRANSITO",
                    eb."CANT_PRODUCCION",
                    eb."CANT_PEDIDA",
                    eb."CONGELADO",
                    eb."FECHA_CONG",
                    eb."BLOQUEA_TRANS",
                    eb."FECHA_DESCONG",
                    c."DESCRIPCION" as category,
                    d."DESCRIPCION" as implemento,
                    b."DESCRIPCION" as brand
                FROM "catalog_management_existenciabodega" eb
                JOIN "catalog_management_articulo" a 
                  ON eb."ARTICULO" = a."ARTICULO"
                LEFT JOIN "catalog_management_clasificacion" c 
                  ON c."CLASIFICACION" = a."CLASIFICACION_2"
                LEFT JOIN "catalog_management_clasificacion" d 
                  ON d."CLASIFICACION" = a."CLASIFICACION_1"
                LEFT JOIN "catalog_management_clasificacion" b 
                  ON b."CLASIFICACION" = a."CLASIFICACION_5";
            """,
            reverse_sql="DROP VIEW ims_item_master_view;"
        ),
    ]
