# Generated by Django 5.2.5 on 2025-12-05 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_management", "0048_auto_20251204_0945"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP MATERIALIZED VIEW IF EXISTS ims_inventory_aging_summary;
                CREATE MATERIALIZED VIEW ims_inventory_aging_summary AS
                WITH articulo_info AS (
                    SELECT
                        a."ARTICULO",
                        a."CLASIFICACION_2",
                        COALESCE(c."DESCRIPCION", 'Otros') AS category_description,
                        a."ULTIMO_MOVIMIENTO",
                        a."DESCRIPCION" AS articulo_descripcion
                    FROM catalog_management_articulo a
                    LEFT JOIN catalog_management_clasificacion c
                      ON c."CLASIFICACION" = a."CLASIFICACION_2"
                )
                
                SELECT
                    eb."BODEGA",
                    ai.category_description AS category,
                    eb."ARTICULO",
                    ai.articulo_descripcion AS descripcion,
                
                    -- Age interval and age in days
                    (NOW() - ai."ULTIMO_MOVIMIENTO")::interval AS age_interval,
                    EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO"))::int AS age_days,
                
                    -- Aging bucket logic
                    CASE
                        WHEN EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO")) <= 30 THEN '0-30 days'
                        WHEN EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO")) <= 60 THEN '31-60 days'
                        WHEN EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO")) <= 90 THEN '61-90 days'
                        WHEN EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO")) <= 180 THEN '91-180 days'
                        WHEN EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO")) <= 365 THEN '181-365 days'
                        ELSE '>365 days'
                    END AS aging_bucket,
                
                    -- Totals
                    SUM(eb."CANT_DISPONIBLE") AS total_qty,
                    SUM(eb."CANT_DISPONIBLE" * eb."COSTO_UNT_PROMEDIO_LOC") AS total_value
                
                FROM catalog_management_existenciabodega eb
                LEFT JOIN articulo_info ai
                    ON ai."ARTICULO" = eb."ARTICULO"
                
                WHERE eb."CANT_DISPONIBLE" > 0
                
                GROUP BY
                    eb."BODEGA",
                    ai.category_description,
                    eb."ARTICULO",
                    ai.articulo_descripcion,
                    ai."ULTIMO_MOVIMIENTO"
                
                ORDER BY
                    EXTRACT(DAY FROM (NOW() - ai."ULTIMO_MOVIMIENTO")) DESC;
            """,
            reverse_sql="DROP MATERIALIZED VIEW ims_inventory_aging_summary;"
        ),
    ]
