# Generated by Django 5.2.5 on 2025-12-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0049_auto_20251205_0236"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgingInventorySummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("BODEGA", models.CharField(max_length=4)),
                ("category", models.CharField(max_length=255)),
                ("ARTICULO", models.CharField(max_length=20)),
                ("descripcion", models.CharField(max_length=255)),
                ("age_interval", models.DurationField()),
                ("age_days", models.IntegerField()),
                ("aging_bucket", models.CharField(max_length=30)),
                ("total_qty", models.DecimalField(decimal_places=8, max_digits=28)),
                ("total_value", models.DecimalField(decimal_places=8, max_digits=28)),
            ],
            options={
                "verbose_name": "Aging Inventory Summary",
                "verbose_name_plural": "Aging Inventory Summary",
                "db_table": "ims_inventory_aging_summary",
                "managed": False,
            },
        ),
    ]
