# Generated by Django 5.2.5 on 2025-12-10 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0050_aginginventorysummary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsientoDeDiario",
            fields=[
                ("ASIENTO", models.CharField(max_length=10)),
                ("PAQUETE", models.CharField(max_length=4)),
                ("TIPO_ASIENTO", models.CharField(max_length=4)),
                ("FECHA", models.DateTimeField()),
                ("CONTABILIDAD", models.CharField(max_length=1)),
                ("ORIGEN", models.CharField(max_length=4)),
                ("CLASE_ASIENTO", models.CharField(max_length=1)),
                (
                    "TOTAL_DEBITO_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TOTAL_DEBITO_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TOTAL_CREDITO_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TOTAL_CREDITO_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("ULTIMO_USUARIO", models.CharField(max_length=50)),
                ("FECHA_ULT_MODIF", models.DateTimeField()),
                ("MARCADO", models.CharField(max_length=1)),
                ("NOTAS", models.TextField(blank=True, null=True)),
                (
                    "TOTAL_CONTROL_LOC",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "TOTAL_CONTROL_DOL",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("USUARIO_CREACION", models.CharField(max_length=50)),
                ("FECHA_CREACION", models.DateTimeField()),
                ("DEPENDENCIA", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "DOCUMENTO_GLOBAL",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Asiento De Diario",
                "verbose_name_plural": "Asientos De Diario",
            },
        ),
        migrations.CreateModel(
            name="CgAux",
            fields=[
                ("GUID_ORIGEN", models.CharField(max_length=48)),
                ("TABLA_ORIGEN", models.CharField(max_length=30)),
                ("ASIENTO", models.CharField(max_length=10)),
                ("LINEA", models.IntegerField()),
                ("COMENTARIO", models.TextField(blank=True, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Cg Aux",
                "verbose_name_plural": "Cg Auxs",
            },
        ),
        migrations.CreateModel(
            name="Diario",
            fields=[
                ("ASIENTO", models.CharField(max_length=10)),
                ("CONSECUTIVO", models.IntegerField()),
                ("NIT", models.CharField(blank=True, max_length=20, null=True)),
                ("CENTRO_COSTO", models.CharField(max_length=25)),
                ("CUENTA_CONTABLE", models.CharField(max_length=25)),
                ("FUENTE", models.CharField(max_length=40)),
                ("REFERENCIA", models.CharField(max_length=249)),
                (
                    "DEBITO_LOCAL",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "DEBITO_DOLAR",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "CREDITO_LOCAL",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "CREDITO_DOLAR",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "DEBITO_UNIDADES",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "CREDITO_UNIDADES",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "TIPO_CAMBIO",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "BASE_LOCAL",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "BASE_DOLAR",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("PROYECTO", models.CharField(blank=True, max_length=25, null=True)),
                ("FASE", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "DOCUMENTO_GLOBAL",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Diario",
                "verbose_name_plural": "Diarios",
            },
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                ("LOTE", models.CharField(max_length=15)),
                ("ARTICULO", models.CharField(max_length=20)),
                ("PROVEEDOR", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "LOTE_DEL_PROVEEDOR",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("FECHA_ENTRADA", models.DateTimeField()),
                ("FECHA_VENCIMIENTO", models.DateTimeField()),
                ("FECHA_CUARENTENA", models.DateTimeField()),
                (
                    "CANTIDAD_INGRESADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("ESTADO", models.CharField(max_length=1)),
                ("TIPO_INGRESO", models.CharField(max_length=1)),
                ("NOTAS", models.TextField(blank=True, null=True)),
                ("ULTIMO_INGRESO", models.IntegerField()),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("FECHA_FABRICACION", models.DateTimeField(blank=True, null=True)),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
            },
        ),
        migrations.CreateModel(
            name="CycleCountBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cycle Count Batch",
                "verbose_name_plural": "Cycle Count Batches",
            },
        ),
        migrations.CreateModel(
            name="CycleCountTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("articulo", models.CharField(max_length=20)),
                ("bodega", models.CharField(max_length=4)),
                ("location", models.CharField(max_length=8)),
                ("system_qty", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "physical_qty",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "variance_qty",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "variance_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=28, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COUNTED", "Counted"),
                            ("REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ADJUSTED", "Adjusted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog_management.cyclecountbatch",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cycle Count Task",
                "verbose_name_plural": "Cycle Count Tasks",
            },
        ),
    ]
