# Generated by Django 5.2.5 on 2025-12-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog_management",
            "0051_asientodediario_cgaux_diario_lote_cyclecountbatch_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Paquete",
            fields=[
                ("PAQUETE", models.CharField(max_length=4)),
                ("DESCRIPCION", models.CharField(max_length=40)),
                ("USUARIO_CREADOR", models.CharField(max_length=50)),
                ("ULTIMO_USUARIO", models.CharField(max_length=50)),
                ("FECHA_ULT_ACCESO", models.DateTimeField()),
                ("ULTIMO_ASIENTO", models.CharField(max_length=10)),
                ("DOBLE_ASIENTO", models.CharField(max_length=1)),
                ("MARCADO", models.CharField(max_length=1)),
                (
                    "RowPointer",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("USA_DOBLE_ASIENTO", models.CharField(max_length=1)),
                (
                    "ULTIMO_ASIENTO_CORP",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("NoteExistsFlag", models.BooleanField()),
                ("RecordDate", models.DateTimeField()),
                ("CreatedBy", models.CharField(max_length=50)),
                ("UpdatedBy", models.CharField(max_length=50)),
                ("CreateDate", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Paquete",
                "verbose_name_plural": "Paquetes",
            },
        ),
        migrations.AddField(
            model_name="cyclecountbatch",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
