# Generated by Django 5.2.5 on 2025-12-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0052_paquete_cyclecountbatch_document_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclecountbatch",
            name="paquete_inventario",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="cyclecounttask",
            name="linea",
            field=models.IntegerField(default=0),
        ),
    ]
