# Generated by Django 5.2.5 on 2025-12-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0053_cyclecountbatch_paquete_inventario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclecountbatch",
            name="referencia",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
