# Generated by Django 5.2.5 on 2025-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0054_cyclecountbatch_referencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cyclecountbatch",
            name="document_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
