# Generated by Django 5.2.5 on 2025-12-15 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0055_alter_cyclecountbatch_document_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cyclecounttask",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                related_query_name="task",
                to="catalog_management.cyclecountbatch",
            ),
        ),
    ]
