# Generated by Django 5.2.5 on 2025-12-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0056_alter_cyclecounttask_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoltWintersForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=20)),
                ("forecast_month", models.DateField()),
                (
                    "forecast_quantity",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Holt-Winters Forecast",
                "verbose_name_plural": "Holt-Winters Forecasts",
            },
        ),
        migrations.CreateModel(
            name="ProphetForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=20)),
                ("forecast_month", models.DateField()),
                (
                    "forecast_quantity",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "forecast_lower",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "forecast_upper",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prophet Forecast",
                "verbose_name_plural": "Prophet Forecasts",
            },
        ),
        migrations.CreateModel(
            name="SarimaForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=20)),
                ("forecast_month", models.DateField()),
                (
                    "forecast_quantity",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sarima Forecast",
                "verbose_name_plural": "Sarima Forecasts",
            },
        ),
    ]
