# Generated by Django 5.2.5 on 2025-12-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0063_auto_20251223_0853"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE
                OR REPLACE VIEW "ims_class_abc_usage" AS
                SELECT
                    "ARTICULO",
                    total_sales_value,
                    CASE
                        WHEN cumulative_percent <= 70 THEN 'Class A'
                        WHEN cumulative_percent <= 90 THEN 'Class B'
                        ELSE 'Class C'
                    END AS abc_class
                FROM (
                WITH item_sales AS (
                    SELECT
                        "ARTICULO",
                        SUM("SALES_AMOUNT") AS total_sales_value
                    FROM ims_items_sales_history
                    WHERE "DS" >= CURRENT_DATE - INTERVAL '1 year'
                    GROUP BY "ARTICULO"
                ),
                ranked_sales AS (
                    SELECT
                        "ARTICULO",
                        total_sales_value,
                        SUM(total_sales_value) OVER () AS grand_total,
                        SUM(total_sales_value) OVER (
                            ORDER BY total_sales_value DESC
                        ) AS cumulative_value
                    FROM item_sales
                )
                SELECT
                    "ARTICULO",
                    total_sales_value,
                    ROUND((cumulative_value / grand_total) * 100, 2) AS cumulative_percent
                FROM ranked_sales
                ORDER BY total_sales_value DESC    -- previous query here
                ) t;
                """,
            reverse_sql="DROP VIEW ims_class_abc_usage;"
        ),
    ]
