# Generated by Django 5.2.5 on 2025-12-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0065_auto_20251226_0819"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE
                OR REPLACE VIEW "ims_holt_winters_forecast_view" AS
                WITH forecast_per_item AS (
                    SELECT
                        article AS articulo,
                        SUM(forecast_quantity) AS total_forecast
                    FROM catalog_management_holtwintersforecast
                    GROUP BY article
                ),
                stock_per_item AS (
                    SELECT
                        "ARTICULO",
                        SUM("CANT_DISPONIBLE" + "CANT_TRANSITO") AS total_available,
                        SUM("CANT_DISPONIBLE") As cant_disp,
                        SUM("CANT_TRANSITO") AS cant_trans,
                        SUM("CANT_RESERVADA") AS cant_reserve,

                        -- weighted average cost
                        SUM("CANT_DISPONIBLE" * "COSTO_UNT_PROMEDIO_LOC")
                        / NULLIF(
                            SUM("CANT_DISPONIBLE"),
                            0
                        ) AS avg_cost
                    FROM catalog_management_existenciabodega
                    WHERE "COSTO_UNT_PROMEDIO_LOC" > 0
                    GROUP BY "ARTICULO"
                )
                SELECT
                    s."ARTICULO",

                    s.total_available,
                    s.avg_cost,
                    f.total_forecast,

                    -- available percentage (1.5 = 150%)
                    (s.total_available
                    / NULLIF(f.total_forecast, 0)) AS available_perc,

                    -- overstock quantity
                    s.total_available - f.total_forecast AS overstock_quantity,

                    -- overstock value
                    (s.total_available - f.total_forecast) * s.avg_cost AS overstock_value,
                       s.cant_disp,
                       s.cant_trans,
                       s.cant_reserve                    

                FROM stock_per_item s
                INNER JOIN forecast_per_item f
                ON f.articulo = s."ARTICULO"

                ORDER BY
                    overstock_value DESC,
                    available_perc DESC;
                """,
            reverse_sql="DROP VIEW ims_holt_winters_forecast_view;"
        ),
    ]
