# Generated by Django 5.2.5 on 2026-01-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0069_auto_20251230_0618"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    CREATE
                    OR REPLACE VIEW "ims_class_abc_usage" AS
                    SELECT
                        "ARTICULO",
                        total_sales as total_sales_value,
                        CASE
                            WHEN cumulative_percent <= 70 THEN 'Class A'
                            WHEN cumulative_percent <= 90 THEN 'Class B'
                            ELSE 'Class C'
                        END AS abc_class
                    FROM (
                    WITH item_sales AS (
                        SELECT
                            "ARTICULO",
                            SUM("Y") AS total_sales
                        FROM ims_items_sales_history
                        WHERE "DS" >= CURRENT_DATE - INTERVAL '1 year'
                        GROUP BY "ARTICULO"
                    ),
                    ranked_sales AS (
                        SELECT
                            "ARTICULO",
                            total_sales,
                            SUM(total_sales) OVER () AS grand_total,
                            SUM(total_sales) OVER (
                                ORDER BY total_sales DESC
                            ) AS cumulative_value
                        FROM item_sales
                    )
                    SELECT
                        "ARTICULO",
                        total_sales,
                        ROUND((cumulative_value / grand_total) * 100, 2) AS cumulative_percent
                    FROM ranked_sales
                    ORDER BY total_sales DESC    -- previous query here
                    ) t;
                    """,
            reverse_sql="DROP VIEW ims_class_abc_usage;"
        ),
    ]
