# Generated by Django 5.2.5 on 2026-01-20 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog_management", "0070_auto_20260106_0559"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
        DROP MATERIALIZED VIEW IF EXISTS "ims_items_sales_history" CASCADE;
        CREATE MATERIALIZED VIEW "ims_items_sales_history" AS
        SELECT
              d."ARTICULO"                          AS "ARTICULO",
              (f."FECHA"::date) AS "DS",
              SUM(d."CANTIDAD")                     AS "Y",
              SUM(d."PRECIO_TOTAL")                 AS "SALES_AMOUNT",
              CASE 
                    WHEN a."TIPO" = 'M' THEN 'Materia Prima'
                    WHEN a."TIPO" = 'T' THEN 'Terminado'
                    WHEN a."TIPO" = 'K' THEN 'Kit'
                    WHEN a."TIPO" = 'C' THEN 'Coproducto'
                    WHEN a."TIPO" = 'E' THEN 'SemiElaborado'
                    WHEN a."TIPO" = 'U' THEN 'Suministro'
                    WHEN a."TIPO" = 'Q' THEN 'Material'
                    ELSE 'Physical'
		     END AS TIPO_ITEM
        FROM catalog_management_facturalinea d
        JOIN catalog_management_factura f
          ON f."FACTURA" = d."FACTURA"
          AND f."TIPO_DOCUMENTO" = d."TIPO_DOCUMENTO"
          AND f."TIPO_DOCUMENTO" = 'F'
        JOIN catalog_management_articulo a
          ON a."ARTICULO" = d."ARTICULO"
        WHERE
          -- only last 5 years (relative to CURRENT_DATE)
          f."FECHA"::date >= (CURRENT_DATE - INTERVAL '5 years')
          -- ignore obviously cancelled headers/lines (attempt to cover common values)
          AND COALESCE(UPPER(f."ANULADA"), 'N') NOT IN ('S')
          AND COALESCE(UPPER(d."ANULADA"), 'N') NOT IN ('S')
          -- ignore zero or negative quantities (adjust if you want returns included)
          AND COALESCE(d."CANTIDAD", 0) > 0
          AND a."TIPO" NOT IN ('V', 'F', 'O', 'L')
        GROUP BY d."ARTICULO", a."TIPO", f."FECHA"::date;   
    """,
            reverse_sql="DROP MATERIALIZED VIEW ims_items_sales_history;"
        )
    ]
