# Generated by Django 5.2.5 on 2026-01-20 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_management", "0073_auto_20260120_0227"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ABCUsageView",
            fields=[
                (
                    "ARTICULO",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "total_sales_value",
                    models.DecimalField(decimal_places=8, max_digits=30),
                ),
                ("abc_class", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "ims_class_abc_usage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ABCValueView",
            fields=[
                (
                    "ARTICULO",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "total_sales_value",
                    models.DecimalField(decimal_places=8, max_digits=30),
                ),
                ("abc_class", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "ims_class_abc_value",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HoltWintersForecastView",
            fields=[
                (
                    "ARTICULO",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "total_available",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("avg_cost", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "total_forecast",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "available_perc",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "overstock_quantity",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "overstock_value",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("cant_disp", models.DecimalField(decimal_places=8, max_digits=28)),
                ("cant_trans", models.DecimalField(decimal_places=8, max_digits=28)),
                ("cant_reserve", models.DecimalField(decimal_places=8, max_digits=28)),
            ],
            options={
                "db_table": "ims_holt_winters_forecast_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ItemLeadDaysView",
            fields=[
                (
                    "ARTICULO",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("DESCRIPCION", models.CharField(max_length=254)),
                ("UNIDAD_ALMACEN", models.CharField(max_length=6)),
                (
                    "EXISTENCIA_MINIMA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "EXISTENCIA_MAXIMA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "PUNTO_DE_REORDEN",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_DISPONIBLE",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_RESERVADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "CANT_NO_APROBADA",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("CANT_VENCIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("CANT_TRANSITO", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "CANT_PRODUCCION",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("CANT_PEDIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("CANT_REMITIDA", models.DecimalField(decimal_places=8, max_digits=28)),
                ("CONGELADO", models.CharField(max_length=1)),
                ("total_qty", models.DecimalField(decimal_places=8, max_digits=28)),
                ("EMBARQUE", models.CharField(max_length=10)),
                ("SHIP_EMISION", models.DateTimeField(blank=True, null=True)),
                ("SHIP_CONFIR", models.DateTimeField(blank=True, null=True)),
                ("SHIP_CRM", models.DateTimeField(blank=True, null=True)),
                ("SHIP_PLANTA", models.DateTimeField(blank=True, null=True)),
                ("PROVEEDOR", models.CharField(max_length=20)),
                ("PROVEEDOR_NOMBRE", models.CharField(max_length=150)),
                ("PROVEEDOR_PAIS", models.CharField(max_length=4)),
                ("LEAD_TIME_DAYS", models.IntegerField()),
            ],
            options={
                "db_table": "ims_item_lead_days_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProphetForecastView",
            fields=[
                (
                    "ARTICULO",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "total_available",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("avg_cost", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "total_forecast",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "available_perc",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "overstock_quantity",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "overstock_value",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("cant_disp", models.DecimalField(decimal_places=8, max_digits=28)),
                ("cant_trans", models.DecimalField(decimal_places=8, max_digits=28)),
                ("cant_reserve", models.DecimalField(decimal_places=8, max_digits=28)),
            ],
            options={
                "db_table": "ims_prophet_forecast_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SarimaForecastView",
            fields=[
                (
                    "ARTICULO",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "total_available",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("avg_cost", models.DecimalField(decimal_places=8, max_digits=28)),
                (
                    "total_forecast",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "available_perc",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "overstock_quantity",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "overstock_value",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                ("cant_disp", models.DecimalField(decimal_places=8, max_digits=28)),
                ("cant_trans", models.DecimalField(decimal_places=8, max_digits=28)),
                ("cant_reserve", models.DecimalField(decimal_places=8, max_digits=28)),
            ],
            options={
                "db_table": "ims_sarima_forecast_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SPDispatchHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_number",
                    models.CharField(
                        default="FO-AL-003", editable=False, max_length=20
                    ),
                ),
                ("dispatch_date", models.DateField()),
                (
                    "exit_type",
                    models.CharField(
                        choices=[
                            ("REPARATION", "Reparación"),
                            ("SAMPLE", "Muestra"),
                            ("PROOF", "Prueba"),
                            ("CUSTOMER_PROPERTY", "Propiedad del Cliente"),
                            ("OTHERS", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "exit_type_others",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                (
                    "centro_costo",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Active Project ID/Name",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("observations", models.TextField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatches_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Exit Form",
            },
        ),
        migrations.CreateModel(
            name="SPDispatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=28)),
                ("unit_of_measure", models.CharField(max_length=6)),
                (
                    "specifications",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "serial_code",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        db_column="ARTICULO",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog_management.articulo",
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog_management.spdispatchheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch Item",
                "unique_together": {("header", "article")},
            },
        ),
        migrations.CreateModel(
            name="SPReturnHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField()),
                ("reason_for_return", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="catalog_management.spdispatchheader",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Form",
            },
        ),
        migrations.CreateModel(
            name="SPReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_returned",
                    models.DecimalField(decimal_places=8, max_digits=28),
                ),
                (
                    "dispatch_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog_management.spdispatchitem",
                    ),
                ),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returned_items",
                        to="catalog_management.spreturnheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Item",
                "unique_together": {("header", "dispatch_item")},
            },
        ),
    ]
