# Generated by Django 5.2.5 on 2026-04-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog_management",
            "0074_abcusageview_abcvalueview_holtwintersforecastview_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
    DROP MATERIALIZED VIEW IF EXISTS "ims_inventory_audit";
    CREATE MATERIALIZED VIEW "ims_inventory_audit" AS
    WITH LatestSnapshot AS (
        SELECT 
            *, 
            ROW_NUMBER() OVER (PARTITION BY "ARTICULO", "BODEGA" ORDER BY "FECHA_CIERRE" DESC) AS rn
        FROM catalog_management_existenciacierre
    )
    SELECT 
        C."FECHA_CIERRE",
        B."ARTICULO",
        B."BODEGA",

        -- CURRENT INVENTORY (from EXISTENCIA_BODEGA)
        B."CANT_DISPONIBLE" AS current_disponible,
        B."CANT_RESERVADA" AS current_reservada,
        B."CANT_NO_APROBADA" AS current_no_aprobada,
        B."CANT_VENCIDA" AS current_vencida,
        B."CANT_REMITIDA" AS current_remitida,

        -- SNAPSHOT INVENTORY (from EXISTENCIA_CIERRE)
        C."CANT_DISPONIBLE" AS snap_disponible,
        C."CANT_RESERVADA" AS snap_reservada,
        C."CANT_NO_APROBADA" AS snap_no_aprobada,
        C."CANT_VENCIDA" AS snap_vencida,
        C."CANT_REMITIDA" AS snap_remitida,

        -- DIFFERENCES (Current – Snapshot)
        (B."CANT_DISPONIBLE" - C."CANT_DISPONIBLE") AS diff_disponible,
        (B."CANT_RESERVADA" - C."CANT_RESERVADA") AS diff_reservada,
        (B."CANT_NO_APROBADA" - C."CANT_NO_APROBADA") AS diff_no_aprobada,
        (B."CANT_VENCIDA" - C."CANT_VENCIDA") AS diff_vencida,
        (B."CANT_REMITIDA" - C."CANT_REMITIDA") AS diff_remitida,

        -- COSTS (snapshot side)
        -- C."COSTO_FISC_UNT_LOC",
        -- C."COSTO_FISC_UNT_DOL",
        C."COSTO_COMP_UNT_LOC",
        C."COSTO_COMP_UNT_DOL",

        -- COSTS (from EXISTENCIA_BODEGA)
        -- B."COSTO_UNT_ESTANDAR_LOC",
        -- B."COSTO_UNT_ESTANDAR_DOL",
        B."COSTO_UNT_PROMEDIO_LOC",
        B."COSTO_UNT_PROMEDIO_DOL",

        -- DIFFERENCES (Current – Snapshot)
        -- (B."COSTO_UNT_ESTANDAR_LOC" - C."COSTO_FISC_UNT_LOC") AS diff_costo_fisc_loc,
        -- (B."COSTO_UNT_ESTANDAR_DOL" - C."COSTO_FISC_UNT_DOL") AS diff_costo_fisc_dol,
        (B."COSTO_UNT_PROMEDIO_LOC" - C."COSTO_COMP_UNT_LOC") AS diff_costo_comp_loc,
        (B."COSTO_UNT_PROMEDIO_DOL" - C."COSTO_COMP_UNT_DOL") AS diff_costo_comp_dol,
        -- For traceability
        B."RecordDate" AS current_record_date,
        C."RecordDate" AS snapshot_record_date
    FROM catalog_management_existenciabodega AS B
    LEFT JOIN LatestSnapshot AS C
    ON B."ARTICULO" = C."ARTICULO" AND B."BODEGA" = C."BODEGA" AND C.rn = 1;     
    """,
            reverse_sql="DROP MATERIALIZED VIEW ims_inventory_audit;"
        )
    ]
