# Generated by Django 5.2.5 on 2025-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vra_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPADMINUsuario',
            fields=[
                ('USUARIO', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=100)),
                ('TIPO', models.CharField(max_length=1)),
                ('ACTIVO', models.CharField(max_length=1)),
                ('REQ_CAMBIO_CLAVE', models.CharField(max_length=1)),
                ('FRECUENCIA_CLAVE', models.SmallIntegerField()),
                ('FECHA_ULT_CLAVE', models.DateTimeField()),
                ('MAX_INTENTOS_CONEX', models.SmallIntegerField()),
                ('CLAVE', models.CharField(blank=True, max_length=68, null=True)),
                ('CORREO_ELECTRONICO', models.CharField(blank=True, max_length=249, null=True)),
                ('TIPO_ACCESO', models.CharField(max_length=1)),
                ('CELULAR', models.CharField(blank=True, max_length=25, null=True)),
                ('RowPointer', models.UUIDField(blank=True, null=True, unique=True)),
                ('TIPO_PERSONALIZADO', models.CharField(blank=True, max_length=256, null=True)),
                ('USAMFA', models.CharField(max_length=1)),
                ('NoteExistsFlag', models.BooleanField()),
                ('RecordDate', models.DateTimeField()),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('CreateDate', models.DateTimeField()),
            ],
            options={
                'db_table': '[ERPADMIN].[USUARIO]',
                'managed': False,
            },
        ),
    ]
