# Generated by Django 5.2.5 on 2025-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vra_backend', '0002_erpadminusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBOAuditSfDeletedRows',
            fields=[
                ('AuditID', models.IntegerField(primary_key=True, serialize=False)),
                ('SchemaName', models.CharField(max_length=128)),
                ('TableName', models.CharField(max_length=128)),
                ('DeletedRP', models.CharField(max_length=36)),
                ('DeletedBy', models.CharField(max_length=128)),
                ('DeletedDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Deleted Row Audit',
                'verbose_name_plural': 'Deleted Rows Audit',
                'db_table': '[DBO].[AUDIT_SF_DELETED_ROWS]',
                'managed': False,
            },
        ),
    ]
