# Generated by Django 5.2.5 on 2025-11-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vra_backend", "0003_dboauditsfdeletedrows"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vraadicional_nomina",
            options={
                "managed": False,
                "verbose_name": "Adicionalnomina",
                "verbose_name_plural": "Adicionalnominas",
            },
        ),
        migrations.AlterModelOptions(
            name="vraadicionalnomina",
            options={
                "managed": False,
                "verbose_name": "Adicional Nomina",
                "verbose_name_plural": "Adicional Nominas",
            },
        ),
        migrations.AlterModelTable(
            name="vraadicional_nomina",
            table="[VRA].[ADICIONALNOMINA]",
        ),
        migrations.AlterModelTable(
            name="vraadicionalnomina",
            table="[VRA].[ADICIONAL_NOMINA]",
        ),
    ]
